version: '3.9'

services:
  mcb.vbo.microservices.statements:
    container_name: mcb.vbo.microservices.statements
    image: ${DOCKER_REGISTRY-}mcbvbomicroservicesstatements
    hostname: statement.service
    build:
      context: .
      dockerfile: MCB.VBO.Microservices.Statements/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq
      #- mcb.vbo.microservices.statements.stateservice
    networks:
      - app-network
    volumes:
      - D:\docker_volume:/app/bin/Debug/net5.0/db

  mcb.vbo.microservices.statements.workerhost:
    container_name: mcb.vbo.microservices.statements.workerhost
    image: ${DOCKER_REGISTRY-}mcbvbomicroservicesstatementsworkerhost
    hostname: statement.workerhost
    build:
      context: .
      dockerfile: MCB.VBO.Microservices.Statements.WorkerHost/Dockerfile
    depends_on:
       - rabbitmq
    networks:
      - app-network
    volumes:
      - D:\docker_volume:/app/bin/Debug/net5.0/db

  rabbitmq:
    container_name: mcb.vbo.microservices.rabbitmq
    image: ${DOCKER_REGISTRY-}rabbitmq:3-management
    hostname: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge