version: '3.9'

services:
  mcb.vbo.microservices.statements:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQ__Server=mcb.vbo.microservices.rabbitmq
      - RabbitMQ__User=guest
      - RabbitMQ__Password=guest
      - RabbitMQ__Port=5672

  mcb.vbo.microservices.statements.workerhost:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
 #     - ServiceConfig__serviceDiscoveryAddress=http://consul:8500
 #     - ServiceConfig__serviceAddress=http://host.docker.internal:5005
 #     - ServiceConfig__serviceName=statementsstate
 #     - ServiceConfig__serviceId=statementsstate-v1

  rabbitmq:
    ports:
      - "5672:5672"
      - "15672:15672"