version: '3.6'

services:
  mcb.vbo.microservices.statements:
    container_name: mcb.vbo.microservices.statements
    image: ${DOCKER_REGISTRY-}mcbvbomicroservicesstatements
    build:
      context: .
      dockerfile: MCB.VBO.Microservices.Statements/Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - app-network

  mcb.vbo.microservices.statements.stateservice:
    container_name: mcb.vbo.microservices.statements.stateservice
    image: ${DOCKER_REGISTRY-}mcbvbomicroservicesstatementsstateservice
    build:
      context: .
      dockerfile: MCB.VBO.Microservices.Statements.StateService/Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - app-network

  rabbitmq:
    container_name: mcb.vbo.microservices.rabbitmq
    image: ${DOCKER_REGISTRY-}rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge