version: '3.9'

services:
  mcb.vbo.microservices.statements:
    container_name: mcb.vbo.microservices.statements
    image: ${DOCKER_REGISTRY-}mcbvbomicroservicesstatements
    hostname: statement.service
    build:
      context: .
      dockerfile: MCB.VBO.Microservices.Statements/Dockerfile
    depends_on:
      - rabbitmq
      - mcb.vbo.microservices.statements.stateservice
    networks:
      - app-network

  mcb.vbo.microservices.statements.stateservice:
    container_name: mcb.vbo.microservices.statements.stateservice
    image: ${DOCKER_REGISTRY-}mcbvbomicroservicesstatementsstateservice
    hostname: statement.stateservice
    build:
      context: .
      dockerfile: MCB.VBO.Microservices.Statements.StateService/Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - app-network

  rabbitmq:
    container_name: mcb.vbo.microservices.rabbitmq
    image: ${DOCKER_REGISTRY-}rabbitmq:3-management
    hostname: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network

  consul:
    image: consul:latest
    command: consul agent -dev -log-level=warn -ui -client=0.0.0.0
    hostname: consul
    container_name: consul
    ports:
      - "8500:8500"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge